### ISSUE TITLE
是否需要安装 kaldi？

### ISSUE THREAD

**Issue by Welsun** [lixucuhk/ASV-anti-spoofing-with-Res2Net#1]
您好，我看到path.sh里面有个KALDI_ROOT,我不太清楚这个地方需要改的是什么路径，我是否需要先安装kaldi[链接](https://github.com/kaldi-asr/kaldi)

**Comment by lixucuhk** [comment]
您好，感谢您对我们工作的兴趣。我们的特征提取是需要用到kaldi的，所以需要安装kaldi。谢谢！
Hi, thanks for your questions and interest in our work. Since we used Kaldi to extract features, you need to install Kaldi before running our scripts. Thank you!

**Comment by Welsun** [comment]
非常感谢您的回答！我已经安装好kaldi，在特征提取的时候又遇到一个问题，在stage3那一步需要执行这一条脚本： python feats_extraction/convertID2index.py --scp-file data/${feat_type}/${name}/feats_slicing.scp --sysID-file data/${feat_type}/${name}/utt2systemID --out-file data/${feat_type}/${name}/utt2index --access-type ${name:0:2} || exit 1
其中有一个文件utt2systemID在cqt中是没有的，所以执行时会报错。但是这个文件在spec目录下是有的，请问这两个文件是否是等价的，我是否需要复制spec中的utt2systemID到cqt中？
非常感谢您的回答！

**Comment by lixucuhk** [comment]
二者是等价的，可以直接复制过去，谢谢！
The utt2systemID files of CQT and Spec features are identical, and we can duplicate one from the other. Thank you!
