### ISSUE TITLE
How to calculate the EER?

### ISSUE THREAD

**Issue by Welsun** [lixucuhk/ASV-anti-spoofing-with-Res2Net#2]
Hi!
After evaluation, I just got some .txt and .eer files. And I want to calculate the EER, can u give me some suggestions?
Thanks for your reply!

**Comment by lixucuhk** [comment]
Sure, thanks for your interest and reminder!
You can either use the Kaldi command with the corresponding *.eer file, e.g. `compute-eer *.eer`, or use the ASVspoof2019 official script with the corresponding *.txt file, e.g. `python scoring/evaluate_tDCF_asvspoof19.py scoring/la_asv_scores/ASVspoof2019.LA.asv.eval.gi.trl.scores.txt *.txt`.
I will add these instructions to the README file. Thank you!

**Comment by Welsun** [comment]
Got it!  Thanks again!
