### ISSUE TITLE
I am not able to run extract_feats.sh

### ISSUE THREAD

**Issue by utkarsh-tyagi** [lixucuhk/ASV-anti-spoofing-with-Res2Net#3]
I am not able to run extract_feats.sh file , it give me error. , i already installed all dependencies in my conda environment and kaldi to run shell script..Error is given below:

$ ./extract_feats.sh --stage 2
Stage 2: extract CQT feats.
Traceback (most recent call last):
  File "D:\asv_res2net\feats_extraction\compute_CQT.py", line 4, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

Why it is giving me numpy error? Please help me out

**Comment by lixucuhk** [comment]
Hi utkarsh-tyagi,

Many thanks for your interest in our work!!!
From your error message, it seems that the NumPy package is not successfully installed in your python. Please try the two suggestions as follows:
1) You installed these packages via conda, so please make sure you go into the exact environment before running codes;
2) You can type "python" in your command window, then type "import numpy" to check whether it is correctly installed in your python.

Thank you!
